### ISSUE TITLE
This is not the official source

### ISSUE THREAD

**Issue by albertvanderhorst** [PeterForth/ForthWin-Download#1]
The official source of winforth is at SourceForge. The readme should at least refer to that. 
Moreover an explanation what this copy has to offer on top of that would be nice.

**Comment by PeterForth** [comment]
You are wrong !  No,  of course this  is not "winforth", you must be confused, and we have nothing to do with that either with a sourceforge distribution.  Please for a description of this project, read the  README.md  supplied and  www.forth2020.org site, is clearly explained. On youtube look for forth2020 and install, you can follow the steps.

**Comment by albertvanderhorst** [comment]
PeterForth schreef op 2020-06-14 18:15:
> You are wrong !  No,  of course this  is not "winforth", you must be
> confused, and we have nothing to do with that either with a
> sourceforge distribution.  Please for a description of this project,
> read the  README.md  supplied and  www.forth2020.org site, is clearly
> explained. On youtube look for forth2020 and install, you can follow
> the steps.

The readme.md starts with
"
The quick installer was disclosed, proceed to install manually.
"
Every project that starts with such a line, instead of the scope of
the project is defective.
In particular it should draw attention to the fact that github is
a copy and the original source is elsewhere.
And of course it should say with so many words that it is an
implementation of Forth, and which dialect.

I see a reference in the title. Sorry, just doesn't count.
Also having references in a title, boy that is bad style!

As an example of how to do it properly see ciforth on github.

My confusion resulted from those defects. You have done nothing
to alleviate the defects.

Groetjes Albert

-- 
Suffering is the prerogative of the strong, the weak -- perish.
Albert van der Horst

**Comment by albertvanderhorst** [comment]
PeterForth schreef op 2020-06-14 18:15:
> Closed #1.

Let me be very blunt. The github website it is not the original
of anything and that should be mentionned in the readme in a prominent
place. That was my issue. What it is not the original, of is neither
here not there. So you were wrong in closing the issue.

Groetjes Albert
-- 
Suffering is the prerogative of the strong, the weak -- perish.
Albert van der Horst

**Comment by PeterForth** [comment]
Albert , the title is self explanatory "ForthWin-Download" is only a download place. This is not the main hub of the project. Start on the web page or watching the videos. Nothing can go wrong.

**Comment by albertvanderhorst** [comment]
PeterForth schreef op 2020-06-15 17:58:
> Albert , the title is self explanatory "ForthWin-Download" is only a
> download place. This is not the main hub of the project. Start on the
> web page or watching the videos. Nothing can go wrong.

First thing I learned about titles is that they are a label, and do not 
convey
information.
Secondly, this meaning is only in your imagination, not in the 
beholders.
So this essential must be in the body.

  You are defensive about the mistakes you make, instead of trying
to learn. I will stop helping you to improve.

--
Suffering is the prerogative of the strong, the weak -- perish.
Albert van der Horst
